In [1]:
import pandas as pd

df = pd.read_csv(
    "IMDB Dataset.csv",
    engine='python',
    encoding='latin-1',
    on_bad_lines='skip'
)

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Data Preprocessing

In this step, we clean the dataset by:
- Removing missing values
- Converting sentiment labels into numerical format

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [8]:
# Remove missing values (if any)
df = df.dropna()

# Convert sentiment to numeric
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

# Check result
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [10]:
df['sentiment'].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

## Data Splitting

In this step, we split the dataset into training, validation, and test sets to properly evaluate model performance.

In [15]:
from sklearn.model_selection import train_test_split

# First split: Train (70%) and Temp (30%)
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df['review'], df['sentiment'],
    test_size=0.3,
    random_state=42
)

# Second split: Validation (15%) and Test (15%)
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts, temp_labels,
    test_size=0.5,
    random_state=42
)

In [17]:
print("Train size:", len(train_texts))
print("Validation size:", len(val_texts))
print("Test size:", len(test_texts))

Train size: 35000
Validation size: 7500
Test size: 7500

## Tokenization using BERT

In this step, we convert text data into token IDs using the BERT tokenizer.
This prepares the data for input into the BERT model.

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
train_encodings = tokenizer(
    list(train_texts),
    truncation=True,
    padding=True,
    max_length=256
)

val_encodings = tokenizer(
    list(val_texts),
    truncation=True,
    padding=True,
    max_length=256
)

test_encodings = tokenizer(
    list(test_texts),
    truncation=True,
    padding=True,
    max_length=256
)